services:
  flaskapp:
    image: musaddique333/backend-flaskapp:latest
    volumes:
      - ./flaskapp:/app/flaskapp
      - ./model:/app/model
    environment:
      MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
      MAIL_PORT: ${{ secrets.MAIL_PORT }}
      MAIL_USE_TLS: ${{ secrets.MAIL_USE_TLS }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      SECURITY_PASSWORD_SALT: ${{ secrets.SECURITY_PASSWORD_SALT }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      DEV_DATABASE_URI: ${{ secrets.DEV_DATABASE_URI }}
      PROD_DATABASE_URI: ${{ secrets.PROD_DATABASE_URI }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      FLASK_ENVIRONMENT: ${{ secrets.FLASK_ENVIRONMENT }}
      REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY }}
    ports:
      - "8000:8000"
    networks:
      - default

  nginx:
    image: musaddique333/backend-nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dinefinder.conf:/etc/nginx/conf.d/dinefinder.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flaskapp
    networks:
      - default

networks:
  default:
    driver: bridge


#  mysql: (This section can be commented out or removed)
#    image: mysql:5.7
#    environment:
#      MYSQL_ROOT_PASSWORD: 
#      MYSQL_DATABASE: 
#    volumes:
#      - mysql-data:/var/lib/mysql
#    ports:
#      - "3306:3306"
