services:
  flaskapp:
    build:
      context: .
      dockerfile: Dockerfile-flask
    volumes:
      - ./flaskapp:/app/flaskapp
      - ./model:/app/model
    environment:
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USE_TLS=${MAIL_USE_TLS}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - SECURITY_PASSWORD_SALT=${SECURITY_PASSWORD_SALT}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DEV_DATABASE_URI=${DEV_DATABASE_URI}
      - PROD_DATABASE_URI=${PROD_DATABASE_URI}
      - FLASK_ENVIRONMENT=${FLASK_ENVIRONMENT}
      - REACT_APP_GOOGLE_MAPS_API_KEY=${REACT_APP_GOOGLE_MAPS_API_KEY}
    ports:
      - "8000:8000"
    networks:
      - default

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dinefinder.conf:/etc/nginx/conf.d/dinefinder.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flaskapp
    networks:
      - default

networks:
  default:
    driver: bridge
