version: '3'

services:
  flaskapp:
    build:
      context: .
      dockerfile: Dockerfile-flask
    volumes:
      - ./flaskapp:/app/flaskapp
      - ./model:/app/model
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - default

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./musaddique.conf:/etc/nginx/conf.d/musaddique.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flaskapp
    networks:
      - default

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  default:
    driver: bridge




#  mysql: (This section can be commented out or removed)
#    image: mysql:5.7
#    environment:
#      MYSQL_ROOT_PASSWORD: mushu
#      MYSQL_DATABASE: flaskapp
#    volumes:
#      - mysql-data:/var/lib/mysql
#    ports:
#      - "3306:3306"
