name: Build and Deploy Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Copy files to EC2
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude '.env' --exclude '.git/' ./ ubuntu@ec2-16-171-170-58.eu-north-1.compute.amazonaws.com:/home/ubuntu/Backend/

    - name: Build and Deploy on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-16-171-170-58.eu-north-1.compute.amazonaws.com << 'EOF'
          cd /home/ubuntu/Backend/
          docker-compose down
          docker rmi $(docker images -q) -f
          docker volume prune -f
          docker network prune -f
          docker system prune -a -f --volumes
          docker-compose build --no-cache
          docker-compose up -d
        EOF
