name: Build and Deploy Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push flaskapp image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile-flask
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/backend-flaskapp:latest

    - name: Build and push nginx image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile-nginx
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/backend-nginx:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Pull and Deploy on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@13.48.125.40 << 'EOF'
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          cd /home/ubuntu/Backend/
          git pull origin main
          docker-compose down
          docker-compose pull
          docker-compose up -d --build
          docker image prune -a -f
        EOF
